build:  
  version: 2016-03-14
  steps:
    builder:
      name: builder
      dockerfile: Dockerfile.builder
      secrets:
        id_rsa:
          type: file
          value: /root/.ssh/dummy_server
